### ISSUE TITLE
Unable to connect, do you have a detailed setup tutorial?

### ISSUE THREAD

**Issue by shaozhai** [JonStratton/mesh-front-py#9] opened 2020-11-03 11:54 UTC
Unable to connect, do you have a detailed setup tutorial?
![image](https://user-images.githubusercontent.com/3293135/97982044-27bceb80-1e0e-11eb-8f86-aa9b5b4f59d0.png)
![image](https://user-images.githubusercontent.com/3293135/97982087-386d6180-1e0e-11eb-8b17-29799d4dac61.png)
![image](https://user-images.githubusercontent.com/3293135/97982122-4327f680-1e0e-11eb-82f7-571e13ef2730.png)
![image](https://user-images.githubusercontent.com/3293135/97982145-4cb15e80-1e0e-11eb-88c4-c7e9912c542a.png)

**Comment by JonStratton** [comment] 2020-11-03 12:43
The documentation is something Ive been needing to clean up for a while. Ill try to write up something better here in the next few day. Perhaps we can work through your issue, and this can become the basis for some debugging documentation? Is "admin123" an existing, working batman-adv node you are trying to mesh with? 

The first thing to look at is if the batman-adv interface was brought up. If you run "ip a" in a terminal on the node, you should see that "bat0" has been associated with your wireless interface, and a new "bat0" interface:
...
3: wlxc4e984095d7f: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master **bat0** state UP group default qlen 1000
    link/ether c4:e9:84:09:5d:7f brd ff:ff:ff:ff:ff:ff
    inet6 fe80::c6e9:84ff:fe09:5d7f/64 scope link 
       valid_lft forever preferred_lft forever
4: **bat0**: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 62:8a:fc:22:21:17 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::608a:fcff:fe22:2117/64 scope link 
       valid_lft forever preferred_lft forever
...

If that's okay, and you have more than one node, you should be able to run "sudo batctl n" and see your neighbors:
[B.A.T.M.A.N. adv 2018.3, MainIF/MAC: wlxc4e984095d7f/c4:e9:84:09:5d:7f (bat0/62:8a:fc:22:21:17 BATMAN_IV)]
IF             Neighbor              last-seen
   wlxc4e984095d7f	  dc:85:de:6d:7d:72    0.164s

If you don't see any neighbors, than the interface is associated with batman-adv, but the nodes are not meshing. If you see and error about no interface, then the wireless interface hasn't been associated with the bat0 interface.

If you do see the neighbors, then you should be able to ping the bat0 ipv4 or ipv6 ip on the other node. Here is the bat0 interface settings for my second node:

jgstratton@meshtest2:~$ ip a
...
4: bat0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 0a:ce:70:5e:63:b3 brd ff:ff:ff:ff:ff:ff
    inet6 **fe80::8ce:70ff:fe5e:63b3**/64 scope link 
       valid_lft forever preferred_lft forever

jgstratton@meshtest1:~$ ping -I bat0 fe80::8ce:70ff:fe5e:63b3
ping6: Warning: source address might be selected on device other than bat0.
PING fe80::8ce:70ff:fe5e:63b3(fe80::8ce:70ff:fe5e:63b3) from :: bat0: 56 data bytes
64 bytes from fe80::8ce:70ff:fe5e:63b3%bat0: icmp_seq=1 ttl=64 time=4.93 ms
....

If you could run through the above items(stopping when you get something funky), then we can maybe figure out whats going on in your case.

**Comment by shaozhai** [comment] 2020-11-03 12:59
![image](https://user-images.githubusercontent.com/3293135/97988092-61462480-1e17-11eb-9c0c-65fa4e0fc9ce.png)

**Comment by shaozhai** [comment] 2020-11-03 13:01
![image](https://user-images.githubusercontent.com/3293135/97988325-c69a1580-1e17-11eb-8d49-cc45fcc34bb1.png)

**Comment by JonStratton** [comment] 2020-11-03 13:39
Okay, it looks like like the bat0 interface is up, but the devices are not meshing. Next step is to "cat /etc/network/interfaces" and check the wireless settings. It should look something like this:

    pre-up sleep 5
    wireless-mode ad-hoc
    wireless-channel 1
    wireless-essid myssid

In order to mesh, these settings must match across nodes. Something I noticed in your above settings, the "Wireless Address" is set. This is kind of carry-over from the old OLSR mesh this thing was originally created from. If the other wireless settings match, you might want to try to remove this setting by commenting it out in the file (if you are comfortable with terminal editing) or with mesh-front-py by just deleting the value and saving, then rebooting.

If this works for you, I will also remove the "Wireless Address" from the "Mesh" button for batman-adv.

**Comment by shaozhai** [comment] 2020-11-03 14:45
![image](https://user-images.githubusercontent.com/3293135/97999467-4fb84900-1e26-11eb-83d3-a6c09d827530.png)

**Comment by shaozhai** [comment] 2020-11-03 14:59
![image](https://user-images.githubusercontent.com/3293135/98001142-44661d00-1e28-11eb-9cfa-6249745799fa.png)

**Comment by shaozhai** [comment] 2020-11-03 15:01
![image](https://user-images.githubusercontent.com/3293135/98001330-77a8ac00-1e28-11eb-9f76-73dcaaad35de.png)

**Comment by shaozhai** [comment] 2020-11-04 00:48
Still can't connect！

**Comment by JonStratton** [comment] 2020-11-04 01:11
Im going to try to reproduce your above settings on my test mesh here over the next hour or so.

**Comment by shaozhai** [comment] 2020-11-04 01:39
![image](https://user-images.githubusercontent.com/3293135/98059229-8ff8e500-1e81-11eb-8d0c-a15678011cd0.png)
Can you assist remotely？

**Comment by shaozhai** [comment] 2020-11-04 01:42
teamviewer
1 016 386 757
3813

**Comment by JonStratton** [comment] 2020-11-04 01:46
Nah, I dont do the team viewer stuff for security reasons. 

I was able to clone your settings and test them on my mesh and it seemed to mesh properly. After you removed the "Wireless Address", were you able to see anything after rebooting and running the "sudo batctl n" command? If that last fix was successful, you should at least see a Neighbor:
[B.A.T.M.A.N. adv 2018.3, MainIF/MAC: wlxc4e984095d7f/c4:e9:84:09:5d:7f (bat0/9e:87:20:80:26:92 BATMAN_IV)]
IF             Neighbor              last-seen
   **wlxc4e984095d7f	  dc:85:de:6d:7d:72    0.172s**

If that doesn't work, there is a chance that your wireless device doesn't support wireless ad-hoc networking. I'm looking up the command that you can run to see if your device is supported.

**Comment by shaozhai** [comment] 2020-11-04 01:49
![image](https://user-images.githubusercontent.com/3293135/98059814-01856300-1e83-11eb-99b9-fdace271aec1.png)

**Comment by shaozhai** [comment] 2020-11-04 01:51
It was normal for my hardware to use HSMM PI before

**Comment by JonStratton** [comment] 2020-11-04 01:55
Fantastic! It looks like the bat0 interfaces on both devices see each other. So now its just a matter of tweaking the settings to do what you are looking at doing. So, I would expect one of your nodes has a connection you want to share with another, correct?

Note to self; fix the Wireless Address population thing for batman-adv based meshes.
Side point; for documentation, the commands I was looking for where "iw list | grep -i mesh" and "iw list | grep -i IBSS" for checking if the device supports meshing.

**Comment by shaozhai** [comment] 2020-11-04 01:57
![image](https://user-images.githubusercontent.com/3293135/98060257-24fcdd80-1e84-11eb-901f-d01c5224c029.png)

**Comment by shaozhai** [comment] 2020-11-04 01:59
![image](https://user-images.githubusercontent.com/3293135/98060320-452c9c80-1e84-11eb-8802-3cbed8ce6ee2.png)
orsl

**Comment by shaozhai** [comment] 2020-11-04 01:59
The ORSL service doesn't seem to start

**Comment by JonStratton** [comment] 2020-11-04 02:04
Okay, that's interesting. This package supports two different types of mesh networks; OLSR and batman-adv. If you are trying to use this with an existing HSMM PI / AREDN / Hammnet mesh network, you would indeed need to choose OLSR. If you are just trying to create a quick mesh, batman-adv is the way to go. 

So are you needing this to work with OLSR for some legacy reasons? Or are you just trying to set up a quick mesh with some devices laying around?

**Comment by shaozhai** [comment] 2020-11-04 02:08
Yes, I just want  just trying to set up a quick mesh with some devices laying around!

**Comment by JonStratton** [comment] 2020-11-04 02:18
Okay, dont worry about OLSR then because that's an old mesh technology. 

On the node that has the internet connection you want to share across your network, you need to do the following:
Go into the "Mesh" settings and select the network interface that has the internet connection from "Share Internet Uplink". 
On the "Mesh Interface Type" section, select "static". Then save. This will set up IP tables to forward packets between interfaces.
Next, go to the "DHCP Server" settings and make sure "bat0" is selected. You might need to set up an IP range. This will make this node a DHCP server.

One the node without the internet connection, go into the "Mesh" settings and set "Mesh Interface Type" to "dhcp". This will tell this node to get its IP settings from the node with the internet connection. 

Then reboot both nodes. The node without the internet connection should have an IP address inside of the IP range set in the node with the internet connections "DHCP Server" settings when you run the "ip a" command.

**Comment by shaozhai** [comment] 2020-11-04 02:27
![image](https://user-images.githubusercontent.com/3293135/98062140-61cad380-1e88-11eb-88b3-e23007a3473c.png)

**Comment by shaozhai** [comment] 2020-11-04 02:29
![image](https://user-images.githubusercontent.com/3293135/98062185-77d89400-1e88-11eb-80fa-3b389df38193.png)
Seems unable to set up DHCP

**Comment by JonStratton** [comment] 2020-11-04 02:33
Is nanopi-r2 the device with the internet connection you want to share? If so, you need to set "Mesh Interface Type" to "static" and set an IP address and netmask (I use IP 192.168.199.1 / 255.255.255.0). Then after that is saved, you would go into the DHCP Server settings.

**Comment by shaozhai** [comment] 2020-11-04 02:53
![image](https://user-images.githubusercontent.com/3293135/98063870-faaf1e00-1e8b-11eb-9d14-bd86d3392af1.png)

**Comment by JonStratton** [comment] 2020-11-04 02:59
Yup, that looks good. Save it and reboot. Then make sure the node without the internet connection has "Mesh Interface Type" set to dhcp. Then reboot it. You should then see it have an IP address between 100-200 when you run "ip a".

Im shutting down for the night, but Ill take another look in the morning.

**Comment by shaozhai** [comment] 2020-11-04 03:00
![image](https://user-images.githubusercontent.com/3293135/98064309-f9322580-1e8c-11eb-9ba6-e707e7e6004f.png)

**Comment by shaozhai** [comment] 2020-11-04 03:59
![image](https://user-images.githubusercontent.com/3293135/98067685-1834b580-1e95-11eb-8c56-b7239f6ff84d.png)

**Comment by JonStratton** [comment] 2020-11-04 13:56
Ive written some notes around initial setup and adding an internet connection. See "Batman Mesh - Basic" and then "Batman Mesh - Adding an network (internet) gateway" under the main README on https://github.com/JonStratton/mesh-front-py/ . Please take a look and tell me if that helps.

I also added some debuggging notes (nothing new, just some stuff you've seen above). Its a little messed up formatting wise, but I plan on cleaning it up this afternoon when I get off of work (along with Wireless Address bug mentioned above).

**Comment by JonStratton** [comment] 2020-11-05 00:53
Added debugging notes. Added install documentation. Fixed one of the bugs that caused issues with your initial set up. And turned unneeded OLSR off by default.

Ill keep this issue open for another day or so in case you run into any new issues. Thanks for calling this stuff out, it has helped me document this thing a bit better.

**Comment by JonStratton** [comment] 2020-11-06 13:23
Added detailed setup tutorial, and fixed one of the bugs that was causing the issue with connecting.

**Closed** 2020-11-06 13:22 UTC
